defmodule Realworld.Api.Resources.User do
  use Ash.Resource

  actions do
    # Add a set of simple actions. You'll customize these later.
    defaults [:create, :read, :update, :destroy]
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.

    # Add a string type attribute called `:subject`
    attribute :username, :string do
      primary_key? true
      allow_nil? false
    end

    attribute :token, :string do
      sensitive? true
    end

    attribute :bio, :string
    attribute :image, :string

    attribute :email, :string do
      allow_nil? false

      #  problem: "admin@gov" is a valid email address
      constraints match: ~r/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$/
    end

    create_timestamp :createdAt
    update_timestamp :updatedAt
  end

  relationships do
    many_to_many :favorites, Realworld.Api.Resources.Article do
      through Realworld.Api.Resources.UserFavorite
      source_attribute :username
      source_attribute_on_join_resource :username
      destination_attribute_on_join_resource :slug
      destination_attribute :slug
    end

    has_many :comments, Realworld.Api.Resources.Comment do
      source_attribute :username
      destination_attribute :author_username
    end

    has_many :articles, Realworld.Api.Resources.Article do
      source_attribute :username
      destination_attribute :author_username
    end
  end
end
